export const LOGIN_START = 'LOGIN_START';
export const LOGIN_START_SUCCESS = 'LOGIN_START_SUCCESS';
export const LOGIN_START_FAIL = 'LOGIN_START_FAIL';

export const LOGOUT_START = 'LOGOUT_START';
export const LOGOUT_STOP = 'LOGOUT_STOP';

export const REGISTRATION_START = 'REGISTRATION_START';
export const REGISTRATION_START_SUCCESS = 'REGISTRATION_START_SUCCESS';
export const REGISTRATION_START_FAIL = 'REGISTRATION_START_FAIL';

export const UNREGISTER = 'UNREGISTER';

export const SET_USER_DATA = 'SET_USER_DATA';
export const SET_REGISTRATION_DATA = 'SET_REGISTRATION_DATA';

export const LOADER_START = 'LOADER_START';
export const LOADER_STOP = 'LOADER_STOP';

export const TOAST_SHOW = 'TOAST_SHOW';
export const TOAST_HIDE = 'TOAST_HIDE';

export const GET_LIST_DATA_START = 'GET_LIST_DATA_START';
export const GET_LIST_DATA_SUCCESS = 'GET_LIST_DATA_SUCCESS';
export const GET_LIST_DATA_ERROR = 'GET_LIST_DATA_ERROR';

export const GET_LOCATION_START = 'GET_LOCATION_START';
export const GET_LOCATION_SUCCESS = 'GET_LOCATION_SUCCESS';
export const GET_LOCATION_FAIL = 'GET_LOCATION_FAIL';
